version: '3'
services:
  discovery-service:
    build: discovery-service
    ports:
      - 8761:8761
    volumes:
      - ./discovery-service/logs:/logs
    networks:
      - api-network
    environment:
      - JAVA_OPTS=
        -DSERVER_PORT=8761
  config-service:
    build: config-service
    depends_on:
      discovery-service:
        condition: service_healthy
    volumes:
      - ./configurations:/var/configurations
      - ./config-service/logs:/logs
    ports:
      - 8888:8888
    networks:
      - api-network
    environment:
      - JAVA_OPTS=
        -DSERVER_PORT=8888
        -DEUREKA_SERVER=http://discovery-service:8761/eureka
        -DADMIN_SERVER=http://discovery-service:8761/admin
        -Dspring.cloud.config.server.native.searchLocations=/var/configurations
  api-gateway:
    build: api-gateway
    depends_on:
      discovery-service:
        condition: service_healthy
      config-service:
        condition: service_healthy
    ports:
      - 8001:8001
    volumes:
      - ./api-gateway/logs:/logs
    networks:
      - api-network
    environment:
      - JAVA_OPTS=
        -DSERVER_PORT=8001
        -DEUREKA_SERVER=http://discovery-service:8761/eureka
        -DADMIN_SERVER=http://discovery-service:8761/admin
        -DCONFIG_SERVER=http://config-service:8888
  currency-service:
    build: currency-service
    depends_on:
      discovery-service:
        condition: service_healthy
      config-service:
        condition: service_healthy
    ports:
      - 8002:8002
    volumes:
      - ./currency-service/logs:/logs
    networks:
      - api-network
    environment:
      - JAVA_OPTS=
        -DSERVER_PORT=8002
        -DEUREKA_SERVER=http://discovery-service:8761/eureka
        -DADMIN_SERVER=http://discovery-service:8761/admin
        -DCONFIG_SERVER=http://config-service:8888
  time-service:
    build: time-service
    depends_on:
      discovery-service:
        condition: service_healthy
      config-service:
        condition: service_healthy
    ports:
      - 8003:8003
    volumes:
      - ./time-service/logs:/logs
    networks:
      - api-network
    environment:
      - JAVA_OPTS=
        -DSERVER_PORT=8003
        -DEUREKA_SERVER=http://discovery-service:8761/eureka
        -DADMIN_SERVER=http://discovery-service:8761/admin
        -DCONFIG_SERVER=http://config-service:8888
  unit-service:
    build: unit-service
    depends_on:
      discovery-service:
        condition: service_healthy
      config-service:
        condition: service_healthy
    ports:
      - 8004:8004
    volumes:
      - ./unit-service/logs:/logs
    networks:
      - api-network
    environment:
      - JAVA_OPTS=
        -DSERVER_PORT=8004
        -DEUREKA_SERVER=http://discovery-service:8761/eureka
        -DADMIN_SERVER=http://discovery-service:8761/admin
        -DCONFIG_SERVER=http://config-service:8888
networks:
  api-network:
    driver: bridge