management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

spring:
  application:
    name: time-service
  boot:
    admin:
      client:
        url:
        - http://localhost:8761/admin

server:
  port: 8003
