spring:
  cloud:
    gateway:
      routes:
        - id: currency-service
          uri: lb://currency-service
          predicates:
            - Path=/api/currency/**
        - id: time-service
          uri: lb://time-service
          predicates:
            - Path=/api/time/**
        - id: unit-service
          uri: lb://unit-service
          predicates:
            - Path=/api/unit/**
