spring:
  cloud:
    gateway:
      routes:
        - id: currency-service
          uri: http://localhost:8002
          predicates:
            - Path=/currency/**
        - id: time-service
          uri: http://localhost:8003
          predicates:
            - Path=/time/**
        - id: unit-service
          uri: http://localhost:8004
          predicates:
            - Path=/unit/**
